version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      - DB_NAME=${DB_NAME:-products_crud}
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./products_crud.sql:/docker-entrypoint-initdb.d/products_crud.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-products_crud}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: 